# Generated by Django 3.2.7 on 2021-09-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(default=3, max_length=300),
            preserve_default=False,
        ),
    ]
